server:
  port: 8080
spring:
  application:
    name: java-send-service-demo
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: send-service
    redis:
      database: 8
      host: redis://localhost:6379
client:
  host: localhost
  port: 8080
  scheme: http
  path: "/confirm/batch"
  supportedCurrencies: "EUR, CHF, GBP, USD"
  send:
    batch:
      timeoutSeconds: 10
      maxSize: 3
      minSize: 2
      sendSchedulerCron: "0/10 * * * * *"
      timeoutSchedulerCron: "0/5 * * * * *"
