### Test1 POST /send/transaction
POST http://localhost:8080/send/transaction
Content-Type: application/json

{
  "senderIban": "DE75512108001245126199",
  "recipientIban": "GB29NWBK60161331926819",
  "amount": 2.88,
  "currencySymbol": "EUR"
}


### Test2 POST /send/transaction
POST http://localhost:8080/send/transaction
Content-Type: application/json

{
  "senderIban": "GB29NWBK60161331926819",
  "recipientIban": "DE75512108001245126199",
  "amount": 8.88,
  "currencySymbol": "USD"
}

### Test3 GET /resend/failedBatches
GET http://localhost:8080/resend/failedBatches?batchId=8e093990-3ba7-4eea-b3a1-b899b502444f
Content-Type: application/json

### Test4 POST /resend/batch/{batchId}
POST http://localhost:8080/resend/batch/8e093990-3ba7-4eea-b3a1-b899b502444f
Content-Type: application/json
